apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-baseline-job
spec:
  template:
    spec:
      containers:
      - name: mnist-baseline-container
        image: mnist-baseline:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: output-volume
          mountPath: /app/runs
        - name: model-volume
          mountPath: /app/models
      restartPolicy: Never
      volumes:
      - name: output-volume
        hostPath:
          path: /home/tomijuki/DIPLOMSKI/runs
          type: DirectoryOrCreate
      - name: model-volume
        hostPath:
          path: /home/tomijuki/DIPLOMSKI/models
          type: DirectoryOrCreate
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: mnist-ddp
            topologyKey: kubernetes.io/hostname
  backoffLimit: 0
